// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eBot.DbContexts;

namespace eBot.Migrations
{
    [DbContext(typeof(StudyContext))]
    [Migration("20210103143317_MigrationName")]
    partial class MigrationName
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("eBot.Data.Persistent.RememberElementDb", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastTimeRepeated")
                        .HasColumnType("TEXT");

                    b.Property<int>("Progress")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("UserDbId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("VocabularyElementId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserDbId");

                    b.ToTable("RememberElementDb");
                });

            modelBuilder.Entity("eBot.Data.Persistent.UserDb", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompletelyRememberedElements")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastCommand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("eBot.Data.Persistent.VocabularyElementDb", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Example")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Transcription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vocabulary");
                });

            modelBuilder.Entity("eBot.Data.Persistent.RememberElementDb", b =>
                {
                    b.HasOne("eBot.Data.Persistent.UserDb", null)
                        .WithMany("ElementsInProgress")
                        .HasForeignKey("UserDbId");
                });

            modelBuilder.Entity("eBot.Data.Persistent.UserDb", b =>
                {
                    b.Navigation("ElementsInProgress");
                });
#pragma warning restore 612, 618
        }
    }
}
